FROM envoyproxy/envoy-alpine:latest
RUN apk update && apk add python3
RUN python3 --version && pip3 --version
RUN pip3 install -q Flask==0.11.1 requests==2.18.4
ENTRYPOINT ["dumb-init", "/code/service.sh"]
